import Head from "next/head";

type HeaderProps = { titleHeader?: string };

export const Header = ({ titleHeader = "" }: HeaderProps): JSX.Element => (
  <Head>
    <title>{titleHeader}</title>
    <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);
