import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-zinc-900">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h2 className="text-md font-semibold text-amber-300">Home</h2>
          <div className="flex flex-col items-center gap-2">
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase = (): JSX.Element => {
  const session = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {session.data && <span>Logged in as {session.data.user?.name}</span>}
      </p>
      <section className="space-x-8">
        <button
          className="rounded-full bg-zinc-700 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
          onClick={
            session.data
              ? () => void signOut()
              : () =>
                  void signIn("google", {
                    callbackUrl: "/dashboard",
                  })
          }
        >
          {session.data ? "Sign out" : "Sign in"}
        </button>
        {session.data && (
          <Link
            className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition duration-300 ease-in-out hover:bg-white/20 active:bg-white/25"
            href="/dashboard"
          >
            Dashboard →
          </Link>
        )}
      </section>
    </div>
  );
};
